# ESMF self-describing build dependency makefile fragment
# src location Zeus: wd

ESMF_DEP_FRONT     = sis2_cap_mod
ESMF_DEP_INCPATH   = /scratch4/GFDL/gfdlscr/Niki.Zadeh/NEMS/UGCS-Seasonal0.2.DREV80567.sis2/trunk/GFDLcomps-INSTALL/SIS2
ESMF_DEP_CMPL_OBJS = 
ESMF_DEP_LINK_OBJS = /scratch4/GFDL/gfdlscr/Niki.Zadeh/NEMS/UGCS-Seasonal0.2.DREV80567.sis2/trunk/GFDLcomps-INSTALL/SIS2/libsis2_cap.a /scratch4/GFDL/gfdlscr/Niki.Zadeh/NEMS/UGCS-Seasonal0.2.DREV80567.sis2/trunk/GFDLcomps-INSTALL/SIS2/libSIS2.a /scratch4/GFDL/gfdlscr/Niki.Zadeh/NEMS/UGCS-Seasonal0.2.DREV80567.sis2/trunk/GFDLcomps-INSTALL/SIS2/libMOM6.a /scratch4/GFDL/gfdlscr/Niki.Zadeh/NEMS/UGCS-Seasonal0.2.DREV80567.sis2/trunk/GFDLcomps-INSTALL/SIS2/libFMS.a
